
def say_name(name):
....def say_goodbye():
....,,,,print("Don't say me goodbye," + name + "!")

....return say_goodbye

Т.е. вызов say_name(name) не выдаст результата, т.к. внутренняя функция say_goodbye() не вызывается.

f =say_name("Sergey")
f()
Выведет сообщение

Благодаря связке f мы запустили внутреннюю функцию, без ведомой на то причины.


![[Screenshot_20230110-021456.png]]



